spec:
  replicas: 1
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 0.5
              memory: 128Mi
            limits:
              cpu: 1.0
              memory: 256Mi
          env:
            - name: BROKER_URI
              value: amqp://my-broker-amqp-0-svc:5672
            - name: BROKER_USERNAME
              value: admin
            - name: BROKER_PASSWORD
              value: admin
